plugins {
    id "eclipse"
    id "idea"
    id "maven-publish"
    id "net.minecraftforge.gradle" version "[6.0,6.2)"
    id "org.spongepowered.mixin" version "0.7.+"
}

version = project.mod_version
group = project.mod_group_id

base {
    archivesName = project.mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

mixin {
    add sourceSets.main, "${project.mod_id}.refmap.json"
    config "${project.mod_id}.mixins.json"
}

minecraft {
    mappings channel: project.mapping_channel, version: project.mapping_version

    copyIdeResources = true

    runs {
        configureEach {
            workingDirectory project.file("run")

            property "forge.logging.markers", "REGISTRIES"
            property "forge.logging.console.level", "info"

            mods {
                lifelikecamera {
                    source sourceSets.main
                }
            }
        }

        client {
            property "forge.enabledGameTestNamespaces", project.mod_id
        }

        server {
            property "forge.enabledGameTestNamespaces", project.mod_id
            args "--nogui"
        }
    }
}

repositories {
    maven { name = "Shedaniel"; url = "https://maven.shedaniel.me/" }
}

dependencies {
    minecraft "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"

    implementation fg.deobf("me.shedaniel.cloth:cloth-config-forge:11.1.118")

    annotationProcessor "org.spongepowered:mixin:0.8.5:processor"
}

tasks.named("processResources", ProcessResources).configure {
    def replaceProperties = [
        minecraft_version: project.minecraft_version,
        minecraft_version_range: project.minecraft_version_range,
        forge_version: project.forge_version,
        forge_version_range: project.forge_version_range,
        loader_version_range: project.loader_version_range,
        mod_id: project.mod_id,
        mod_name: project.mod_name,
        mod_license: project.mod_license,
        mod_version: project.mod_version,
        mod_authors: project.mod_authors,
        mod_description: project.mod_description
    ]

    inputs.properties replaceProperties

    filesMatching(["META-INF/mods.toml"]) {
        expand replaceProperties
    }
}

jar {
    manifest {
        attributes([
            "Specification-Title": project.mod_id,
            "Specification-Vendor": project.mod_authors,
            "Specification-Version": "1",
            "Implementation-Title": project.mod_name,
            "Implementation-Version": project.mod_version,
            "Implementation-Vendor": project.mod_authors
        ])
    }
    finalizedBy("reobfJar")
}

publishing {
    publications {
        register("mavenJava", MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url = uri(layout.buildDirectory.dir("repo"))
        }
    }
}
